services:

  db:
    image: postgis/postgis:latest
    ports:
      - "5439:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d roga_and_kopyta" ]
      interval: 2s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=roga_and_kopyta
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_volume_test:/var/lib/postgresql/data

  app:
    image: roga-and-kopyta
    container_name: roga_and_kopyta
    command: ["sh", "-c", "uv run up && uv run app"]
    build:
      context: .
      dockerfile: Dockerfile
    env_file: [ .env ]
    ports: [ "${APP_PORT}:${APP_PORT}" ]
    depends_on:
      db:
        condition: service_healthy


volumes:
  db_volume_test: