target-version = "py312"
show-fixes = true
output-format = "concise"
src = ["."]
exclude=["*/migrations/*", "*tmp*.py", ".venv/", "*.ipynb"]
line-length = 88

[lint]
select = [
    "E",
    "W",
    "F",
    "FAST",
    "B",
    "UP",
    "ASYNC",
    "S",
    "BLE",
    "PIE",
    "T20",
    "C4",
    "RET",
    "COM",
    "I",
    "RUF200",
]
ignore = [
#    "E501",
    "B008",
    "W191",
    "B904",
    "COM812",
    "S101",
    "S104",
    "BLE001",
    "RET503",
    "UP038",
]
fixable = ["ALL"]
unfixable = ["B", "N"]

[lint.per-file-ignores]
'__init__.py' = [
    'F401',
    'F403',
    'F405',
]
"tests/*" = ["S101", "D103", "D101", "D102"]

[lint.isort]
lines-between-types = 1
lines-after-imports = 2

[lint.pyupgrade]
keep-runtime-typing = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.mccabe]
max-complexity = 3
